name: web

on:
  push:
    paths:
      - 'web/**'

  workflow_dispatch: 

jobs:  

  resourcegroups:

    runs-on: ubuntu-latest

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SYBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./web

    steps:

      - uses: actions/checkout@v3
        with: 
          node-version: '20'

      - name: 'Terraform init'
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Teraform apply'
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
